<?php

$custom_style .= '
    h1, h2, h3, h4, h5, h6,
    a,
    .button,
    button,
    input[type="button"],
    input[type="reset"],
    input[type="submit"],
    label,
    .label,
    label span,
    .site-title,
    .wishlist_items_number,
    .shopping_bag_items_number,
    #site-navigation-top-bar,
    #site-top-bar .site-top-message,
    .mobile-navigation,
    .main-navigation,
    .variation dd p,
    p.out-of-stock,
    p.stock.available-on-backorder,
    .woocommerce p.out-of-stock,
    .woocommerce div.product p.stock.available-on-backorder,
    .woocommerce-account table.account-orders-table tbody tr td:before,
    .top-headers-wrapper .site-tools ul li a span,
    .woocommerce-result-count,
    .woocommerce-form-coupon-toggle .woocommerce-info,
    .woocommerce-form-login-toggle .woocommerce-info,
    .select2-results__option,
    .woocommerce-breadcrumb,
    .widget_product_search #searchsubmit,
    .widget_search #searchsubmit,
    .widget_product_search .search-submit,
    .widget_search .search-submit,
    .comment-respond label,
    .pswp.pswp--open .pswp__top-bar .pswp__counter,
    blockquote cite,
    .widget .tagcloud a,
    table thead th,
    .woocommerce div.product form.cart div.label label,
    .woocommerce-page div.product form.cart div.label label,
    .woocommerce #content div.product form.cart div.label label,
    .woocommerce-page #content div.product form.cart div.label label,
    span.onsale,
    .woocommerce span.onsale,
    .wc-block-grid__product-onsale,
    .wc-block-grid__product-onsale,
    .woocommerce .cart-collaterals .cart_totals table th,
    .woocommerce-page .cart-collaterals .cart_totals table th,
    .woocommerce .cart-collaterals .shipping-calculator-button,
    .woocommerce-page .cart-collaterals .shipping-calculator-button,
    .woocommerce form .form-row label,
    .woocommerce-page form .form-row label,
    .site-tools,
    .post-edit-link,
    .comment-edit-link,
    .comment-reply-link,
    .slider_button,
    .go_home,
    .filters_button,
    .woocommerce-ordering,
    .add_to_wishlist,
    .woocommerce p.out-of-stock,
    .woocommerce div.product p.stock.available-on-backorder,
    .wishlist-in-stock,
    .wishlist-out-of-stock,
    tr.shipping > td:first-of-type,
    .checkout_coupon .woocommerce-info,
    .woocommerce-wishlist .wishlist-empty,
    .check_label_radio,
    .order_details .title,
    .order_details li,
    .customer_details dt,
    .account_view_link,
    p.demo_store,
    .order_details_footer tr td:first-of-type,
    .wpcf7,
    .widget_layered_nav ul li.chosen,
    .widget_layered_nav_filters ul li.chosen a,
    .product_meta > span,
    .woocommerce table.shop_attributes th,
    .woocommerce-page table.shop_attributes th,
    .wpb_tour.wpb_content_element .wpb_tabs_nav li a,
    .mobile-menu-text,
    .trigger-share-list,
    .shortcode_banner_simple_height_bullet span,
    .select2-container .select2-selection,
    select.topbar-language-switcher,
    select.wcml_currency_switcher,
    .blog-isotope .more-link,
    .blog-isotope .post_meta_archive,
    .product_after_shop_loop .price,
    .yith-wcwl-wishlistaddedbrowse a,
    .yith-wcwl-wishlistexistsbrowse a,
    .woocommerce-message a,
    .woocommerce .cart-collaterals .cart-subtotal .amount,
    .woocommerce .cart-collaterals .shipping,
    .woocommerce .cart-collaterals .cart-subtotal,
    .post_header_date,
    .blog-list-date,
    .comment-metadata,
    .more-link,
    .vc_btn,
    .nav-previous a,
    .nav-next a,
    .wc-block-grid__product-price,
    .wc-block-order-select label.wc-block-order-select__label,
    .wp-block-latest-posts li .wp-block-latest-posts__post-date,
    .product_meta span a,
    .product_meta span span,
    .comments-title,
    .copyright_text,
    .order_details li strong,
    .wpcf7 input,
    .cart-subtotal .amount,
    .order-total .amount,
    .wpb_tabs .ui-widget,
    .wpb_tour .ui-widget,
    .wpb_accordion .ui-widget,
    .widget ul small.count,
    .content-area blockquote.wp-block-quote p,
    .content-area .wp-block-pullquote p,
    .woocommerce #payment .payment_method_paypal .about_paypal,
    .shortcode_title.main_font,
    .remember-me,
    .woocommerce form .form-row label.inline,
    .woocommerce-page form .form-row label.inline,
    .nav-next-title,
    .nav-previous-title,
    .woocommerce-MyAccount-navigation ul li,
    .woocommerce td.product-name .wc-item-meta,
    .woocommerce td.product-name dl.variation,
    .wc-block-grid__product-add-to-cart *,
    .categories_grid .category_name,
    ul.products li.product .woocommerce-loop-category__title,
    .main-navigation .sub-menu li a,
    .wp-block-latest-posts li a, .wp-block-latest-posts li a,
    .widget_shopping_cart,
    .product p.price,
    .amount,
    .tabs li a,
    .blog-list-day,
    .edit-account legend,
    .add_to_cart_inline .amount,
    .vc_tta-title-text,
    .wc-block-grid__product-title,
    #comments .comment-reply-title,
    .minicart_text,
    .widget_shopping_cart .total *,
    .woocommerce-review__author,
    .comment-reply-title,
    .add_to_wishlist span,
    .woocommerce-ordering .select2-selection__rendered,
    .woocommerce-mini-cart__empty-message,
    .woocommerce nav.woocommerce-pagination ul li span,
    .woocommerce-cart table.shop_table.cart tbody tr td.product-name,
    .woocommerce-cart table.shop_table.cart tbody tr td:before,
    .woocommerce-cart .cart-collaterals .cart_totals table.shop_table tr td:before,
    #site-top-bar .language-and-currency span.select2-selection__rendered,
    .woocommerce-cart .cart-empty,
    table.woocommerce-checkout-review-order-table tbody tr td.product-name,
    .woocommerce table.order_details,
    .woocommerce-account .woocommerce-MyAccount-content > p mark,
    .wishlist_table.mobile li .item-details table.item-details-table td.value,
    table.shop_table tfoot th,
    ul.wc-block-active-filters-list li.wc-block-active-filters-list-item,
    .catalog-page .woocommerce-ordering select.orderby,
    .mrtailor_products_load_more_loader span,
    .main-navigation ul > li.menu-item-info-column .menu-item-description
    {
        font-family: ' . MrTailor_Fonts::get_main_font() . ';
    }

    body,
    p,
    input,
    textarea,
    select,
    .select2-selection__rendered,
    .select2-selection__placeholder,
    .woocommerce .widget_rating_filter ul li a
    {
        font-family: ' . MrTailor_Fonts::get_secondary_font() . ';
    }
';
